In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('tahun-2021-s2---jumlah-penduduk-berdasarkan-tingkat-pendidikan.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [4]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='constant')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [5]:
dataset

Kode Kecamatan    Kecamatan Kode Kelurahan         Kelurahan  \
0         32.73.01     Sukasari  32.73.01.1001          Sukarasa   
1         32.73.01     Sukasari  32.73.01.1002       Gegerkalong   
2         32.73.01     Sukasari  32.73.01.1003             Isola   
3         32.73.01     Sukasari  32.73.01.1004          Sarijadi   
4         32.73.02      Coblong  32.73.02.1001         Cipaganti   
..             ...          ...            ...               ...   
146       32.73.29      Cinambo  32.73.29.1004  Babakan Penghulu   
147       32.73.30  Mandalajati  32.73.30.1001        Jatihandap   
148       32.73.30  Mandalajati  32.73.30.1002   Karang Pamulang   
149       32.73.30  Mandalajati  32.73.30.1003       Pasir Impun   
150       32.73.30  Mandalajati  32.73.30.1004      Sindang Jaya   

     Tidak/Belum Sekolah  Belum Tamat SD  Tamat SD  SLTP  SLTA  D1 dan D2  \
0                   2275            1173      1900  1648  3735        108   
1                   3850            2038      2068  2450  6924        348   
2                   2412            1289      1740  1608  4073        120   
3                   4525            2462      2137  2545  8416        380   
4                   1820            1055      1121  1406  4494         58   
..                   ...             ...       ...   ...   ...        ...   
146                 1331             706      1016  1118  2092         36   
147                 5224            2754      3382  3755  8277         98   
148                 3602            1798      2137  2645  6146         80   
149                 2577            1403      1961  1942  3956         39   
150                 2754            1504      1350  1922  4665         64   

       D3    S1   S2   S3  
0     469  1633  288   43  
1    1280  3662  640  115  
2     502  1557  205   60  
3    1703  4503  633   84  
4     399  1200  103   25  
..    ...   ...  ...  ...  
146   221   736  121   12  
147   820  2207  209   19  
148   548  1589  149    6  
149   329   948   90   16  
150   657  1664  216   30  

[151 rows x 14 columns]

In [6]:
print(X)

[['32.73.01' 'Sukasari' '32.73.01.1001' ... 469 1633 288]
 ['32.73.01' 'Sukasari' '32.73.01.1002' ... 1280 3662 640]
 ['32.73.01' 'Sukasari' '32.73.01.1003' ... 502 1557 205]
 ...
 ['32.73.30' 'Mandalajati' '32.73.30.1002' ... 548 1589 149]
 ['32.73.30' 'Mandalajati' '32.73.30.1003' ... 329 948 90]
 ['32.73.30' 'Mandalajati' '32.73.30.1004' ... 657 1664 216]]


In [7]:
print(y)

[ 43 115  60  84  25  20  27 180  54   6   7  11   6  19   3   8  17   7
   6   2  15   8   9   8   7   3  10  15  15  28  15  17  47  46  24  28
  55  13  36  48  22  43  50  40   9   4   2   1   6   6  33  31   6  10
  11  16  17  41   6  11  13   9   3   4   5  58  22  18   6 131  12   9
   9  28   9  17  33  37  24   5  16  21   0  36   1   4  13   2   8  14
  21   5   6  15   4   4   7   7  34  60  20 181  10  24  17   8  43  61
  97  45  48   0  17  24  98  62  38  42  51  16  99  33 127  11  55  65
  28  56  34  14  48  33  18  17  23   6  57  25  11  25  63   0  21   8
  11   7  12  19   6  16  30]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 469 1633 288]
 [1.0 0.0 0.0 ... 1280 3662 640]
 [1.0 0.0 0.0 ... 502 1557 205]
 ...
 [0.0 0.0 0.0 ... 548 1589 149]
 [0.0 0.0 0.0 ... 329 948 90]
 [0.0 0.0 0.0 ... 657 1664 216]]


In [10]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [11]:
print(y)

[38 59 50 55 25 20 26 62 45  6  7 11  6 19  3  8 17  7  6  2 15  8  9  8
  7  3 10 15 15 27 15 17 41 40 24 27 46 13 32 42 22 38 43 35  9  4  2  1
  6  6 30 29  6 10 11 16 17 36  6 11 13  9  3  4  5 49 22 18  6 61 12  9
  9 27  9 17 30 33 24  5 16 21  0 32  1  4 13  2  8 14 21  5  6 15  4  4
  7  7 31 50 20 63 10 24 17  8 38 51 56 39 42  0 17 24 57 52 34 37 44 16
 58 30 60 11 46 54 27 47 31 14 42 30 18 17 23  6 48 25 11 25 53  0 21  8
 11  7 12 19  6 16 28]


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [13]:
print(X_train)

[[0.0 0.0 0.0 ... 167 438 40]
 [0.0 0.0 0.0 ... 1012 3869 860]
 [0.0 0.0 0.0 ... 371 1130 137]
 ...
 [0.0 0.0 0.0 ... 589 1398 117]
 [0.0 0.0 0.0 ... 1007 3165 367]
 [0.0 0.0 0.0 ... 792 1562 137]]


In [14]:
print(X_test)

[[0.0 0.0 1.0 ... 196 573 47]
 [0.0 0.0 0.0 ... 637 1645 192]
 [0.0 0.0 0.0 ... 620 1478 108]
 ...
 [0.0 0.0 0.0 ... 878 2080 203]
 [0.0 0.0 0.0 ... 820 2207 209]
 [0.0 0.0 0.0 ... 405 1029 59]]


In [15]:
print(y_train)

[ 6 61 31 57  6 10 15 11 56 17  7 16 24  6 44  6 25  4 11 42 46 37 25 51
 18 27  4 60  4 11 24 11  6 50 17 26 47 42 49 16  7 11  2  3  9 34 15 20
 14  7 24 41 46 32 32  0 28 15  8 18  6 42  7  8 12  2 16 39  5  8  0 38
 16  6 10 30 35  7 48 30  8  6  8 12 55 21 15  6 38  1 52 19  8 45 21 13
 38 59 36  9  9  4 62 13  7  6 30 63 15  3 23  9 14 11  5 17 25  9 53 13]


In [16]:
print(y_test)

[ 3 31 17 17 30 17  0  9 27 58  4 20 10 29 24 43  6 22 17 27 21  1 33 22
 54 50 40  2 27 19  5]


In [17]:
from sklearn.preprocessing import StandardScaler as SS
sc = SS()
X_train[:, -1:] = sc.fit_transform(X_train[:, -1:])
X_test[:, -1:] = sc.transform(X_test[:, -1:])

In [18]:
print(X)

[[1.0 0.0 0.0 ... 469 1633 288]
 [1.0 0.0 0.0 ... 1280 3662 640]
 [1.0 0.0 0.0 ... 502 1557 205]
 ...
 [0.0 0.0 0.0 ... 548 1589 149]
 [0.0 0.0 0.0 ... 329 948 90]
 [0.0 0.0 0.0 ... 657 1664 216]]


In [19]:
print(X_test)

[[0.0 0.0 1.0 ... 196 573 -0.805899226513128]
 [0.0 0.0 0.0 ... 637 1645 -0.0595373710027795]
 [0.0 0.0 0.0 ... 620 1478 -0.4919125148846365]
 ...
 [0.0 0.0 0.0 ... 878 2080 -0.0029168164468220317]
 [0.0 0.0 0.0 ... 820 2207 0.027967122401882042]
 [0.0 0.0 0.0 ... 405 1029 -0.7441313488157197]]
